#!/bin/bash
python3 -m py_compile "$PYFILE"
mv "__pycache__/${PYFILE%.py}.cpython-"*".pyc" "${PYFILE}c" 2>/dev/null || python3 -c "import py_compile, os; py_compile.compile(os.environ['PYFILE'], os.environ['PYFILE'] + 'c')"
